---
title: "EF Group Submission Assignment 3"
subtitle: "Group 15" 
author: "Lanlan Hou (2801069), Rick van der Ploeg (2782774), Sebastiaan van Dijen (2769505) and Alfred Sou (2796840)"
output: pdf_document
---

# Question 1

## a.
```{r echo=TRUE,fig.dim=c(5,4),fig.align='center'}
# Load required packages
library(openxlsx)   # Excel file handling
library(lubridate)  # Date/time utilities
library(quantmod)   # Financial data & modeling
library(rugarch)    # GARCH/AR-GARCH models
library(ggplot2)    # Data visualization

raw <- read.xlsx('student_groups_stocks.xlsx', sheet = 1)

groupNumber <- 15
nameOfStock <- raw$Stock.Name[groupNumber]
startDate <- raw$Start.Date[groupNumber]
endDate <- raw$`End.Date.(+10y)`[groupNumber]

# compute the start date of the final five years
originalDate <- as.Date(startDate)
endDate_fiveYears <- originalDate %m+% years(5)

# extract the daily stock price from source
getSymbols(nameOfStock, src = 'yahoo', from = startDate, to = endDate)

# extract the data of first five years
firstFiveYear <- window(HSBC, start = startDate, end = endDate_fiveYears)

# extract the Adjusted Close for the first five years
adjustedPrice_firstFiveYears<- as.numeric(firstFiveYear[,'HSBC.Adjusted'])

# compute the Daily Log Returns for the first five years
compoundedReturns_firstFiveYears <- numeric(length(adjustedPrice_firstFiveYears) - 1)
for(i in (2:length(adjustedPrice_firstFiveYears))){
  compoundedReturns_firstFiveYears[i-1] <- log(adjustedPrice_firstFiveYears[i] / adjustedPrice_firstFiveYears[i-1])
}

# specify AR(1)-GARCH(1,1) model under normal distribution
ar1garch11_spec_norm <- ugarchspec(variance.model = list(model = 'sGARCH',
                                                    garchOrder = c(1, 1)),
                        mean.model = list(armaOrder = c(1, 0),
                        include.mean = TRUE),
                        distribution.model = 'norm')

ar1garch11_fit_norm <- ugarchfit(spec = ar1garch11_spec_norm, 
                                 data = compoundedReturns_firstFiveYears)

ar1garch11_fit_norm@fit$matcoef
```

## b.
```{r echo=TRUE,fig.dim=c(5,4),fig.align='center'}
# extract the data of last five years
lastFiveYear <- window(HSBC, start = endDate_fiveYears, end = endDate)

# extract the Adjusted Close for the next five years
adjustedPrice_lastFiveYears<- as.numeric(lastFiveYear[,'HSBC.Adjusted'])

# compute the Daily Log Returns for the next five years
compoundedReturns_lastFiveYears <- numeric(length(adjustedPrice_lastFiveYears) - 1)
for(i in (2:length(adjustedPrice_lastFiveYears))){
  compoundedReturns_lastFiveYears[i-1] <- log(adjustedPrice_lastFiveYears[i] / adjustedPrice_lastFiveYears[i-1])
}

# extract the estimated parameters
mu_norm <- coef(ar1garch11_fit_norm)['mu']
ar1_norm <- coef(ar1garch11_fit_norm)['ar1']
omege_norm <- coef(ar1garch11_fit_norm)['omega']
alpha1_norm <- coef(ar1garch11_fit_norm)['alpha1']
beta1_norm <- coef(ar1garch11_fit_norm)['beta1']
sum_alphaBeta <- alpha1_norm + beta1_norm

t <- length(compoundedReturns_firstFiveYears)
returns_t <- compoundedReturns_firstFiveYears[t]
eps_t <- ar1garch11_fit_norm@fit$residuals[t]
var_t <- ar1garch11_fit_norm@fit$var[t]

# compute the 1-step ahead variance
oneAhead_var <- omege_norm + alpha1_norm * (eps_t^2) + beta1_norm * (var_t)

forecast_returns <- numeric(length(compoundedReturns_lastFiveYears))
forecast_variance <- numeric(length(compoundedReturns_lastFiveYears))

# compute the returns and variance forecast for the next 5 years
for (i in 1:length(compoundedReturns_lastFiveYears)){
  # Forecast for Log Returns 
  forecast_returns[i] <- (sum(sapply(0:(i-1), function(j) ar1_norm^j)) * mu_norm) + ar1_norm^i * returns_t
  
  # Forecast for Variance
  if (i == 1) {
    forecast_variance[i] <- oneAhead_var
  } else {
    forecast_variance[i] <- (sum(sapply(0:(i-2), 
                                        function(j) sum_alphaBeta^j))) * omege_norm + sum_alphaBeta^(i-1) * oneAhead_var
  }
}

# standardize the Daily Log Returns
standardized_returns <- (compoundedReturns_lastFiveYears - forecast_returns) / forecast_variance

# Distribution of Standardized Returns
returns_df <- data.frame(standardizedReturns = standardized_returns)

ggplot(returns_df, aes(x = standardizedReturns)) +
  geom_histogram(aes(y = after_stat(density), color = 'Empirical Distribution'), 
                 bins = 50, fill = 'skyblue') +
  stat_function(fun = dnorm,
                args = list(mean = mean(standardized_returns, na.rm = TRUE),
                            sd = sd(standardized_returns, na.rm = TRUE)),
                aes(color = 'Normal Distribution'), linewidth = 1, linetype = 'dashed') +
  scale_color_manual(name = "Distributions",
                     values = c('Normal Distribution' = 'black',
                                'Empirical Distribution' = 'blue')) +
  labs(title = 'Distribution of Standardized Returns',
       x = 'Standardized Returns', y = 'Density') +
  theme(legend.position = c(0.95, 0.95),
          legend.justification = c("right", "top"),
          legend.title = element_text(size = 12, face = "bold"),
          legend.text = element_text(size = 10))
ggsave('figures/standardizedReturns_distribution.png', width = 10, height = 6, dpi = 300)

# QQ Plot of Standardized Returns
ggplot(returns_df, aes(sample = standardizedReturns)) +
  stat_qq(shape = 1, color = 'blue', size = 1) +
  stat_qq_line(color = 'red', linewidth = 1) +
  labs(title = 'QQ Plot for HSBC Standardized Log Returns',
       x = 'Theoretical Quantiles', y = 'Sample Quantiles') +
  theme_minimal()
ggsave('figures/standardizedReturns_qqplot.png', dpi = 300)
```

# Question 2

## a.
```{r echo=TRUE, fig.dim=c(5,4),fig.align='center'}
# specify AR(1)-GARCH(1,1) model under student t distribution
ar1garch11_spec_t <- ugarchspec(variance.model = list(model = 'sGARCH',
                                                    garchOrder = c(1, 1)),
                                mean.model = list(armaOrder = c(1, 0),
                                include.mean = TRUE),
                                distribution.model = 'std')

ar1garch11_fit_t <- ugarchfit(spec = ar1garch11_spec_t, 
                              data = compoundedReturns_firstFiveYears)

ar1garch11_fit_t@fit$matcoef
```

## b.
```{r echo=TRUE, fig.dim=c(5,4), fig.align='center'}
# compute the likelihood
logLikelihood_norm <- (likelihood(ar1garch11_fit_norm)) # restricted
logLikelihood_t <- (likelihood(ar1garch11_fit_t)) # unrestricted

# compute the test statistic
LR  <- -2 * (logLikelihood_norm - logLikelihood_t)

degreeOfFreedom  <- 1
criticalValue <- qchisq(0.95, df = degreeOfFreedom)
pValue <- 1 - pchisq(LR, df = degreeOfFreedom)

likelihoodRatioTest_result_df <- data.frame(LogL_Norm = logLikelihood_norm,
                                            LogL_t = logLikelihood_t,
                                            TestStatistic = LR,
                                            DF = degreeOfFreedom,
                                            CriticalValue = criticalValue,
                                            PValue = pValue)
likelihoodRatioTest_result_df 
```