---
title: "EF Group Submission Assignment 1"
subtitle: "Group 15" 
author: "Lanlan Hou (2801069), Rick van der Ploeg (2782774), Sebastiaan van Dijen (2769505) and Alfred Sou (2796840)"
output: pdf_document
---

# Question 1

## a.
```{r echo=TRUE,fig.dim=c(5,4),fig.align='center'}
library(openxlsx)
raw <- read.xlsx('student_groups_stocks.xlsx', sheet = 1)

groupNumber <- 15
nameOfStock <- raw$Stock.Name[groupNumber]
startDate <- raw$Start.Date[groupNumber]
endDate <- raw$`End.Date.(+10y)`[groupNumber]

# Extract the daily stock price from source
library(quantmod)
getSymbols(nameOfStock, src = 'yahoo', from = startDate, to = endDate)
date <- index(HSBC)

# Adjusted Close
adjustedPrice <- as.numeric(HSBC[,'HSBC.Adjusted'])

# Log Returns
compoundedReturns <- numeric(length(adjustedPrice) - 1)
for(i in (2:length(adjustedPrice))){
  compoundedReturns[i-1] <- log(adjustedPrice[i] / adjustedPrice[i-1])
}

library(ggplot2)
prices_df <- data.frame(date = date, adjustedPrice = adjustedPrice)
returns_df <- data.frame(date = date[2:length(date)], compoundedReturns = compoundedReturns)

# Plot of daily stock price
ggplot(prices_df, aes(x = date, y = adjustedPrice)) +
  geom_line(color = 'navy', linewidth = 1) +
  geom_smooth(color = 'orange', se = FALSE) +
  labs(
    title = paste(nameOfStock, 'Adjusted Stock Prices with Trend (2010 - 2020)'),
    x = 'Year',
    y = 'Adjusted Close Price') +
  theme_minimal()
ggsave('figures/prices_plot.png', dpi = 300)

# Plot of daily log returns
ggplot(returns_df, aes(x = date, y = compoundedReturns)) +
  geom_line(color = 'navy', na.rm = TRUE, linewidth = 1) +
  labs(
    title = paste(nameOfStock, 'Daily Log Returns(2010 - 2020)'),
    x = 'Year',
    y = 'Log Returns') +
  theme_minimal()
ggsave('figures/returns_plot.png', dpi = 300)
```

## b.
```{r echo=TRUE,fig.dim=c(5,4),fig.align='center'}
# Compute some relevant summary statistics of Adjusted Close
library(moments)
price_mean <- mean(adjustedPrice)
price_stdev <- sd(adjustedPrice)
price_minimum <- min(adjustedPrice)
price_maximum <- max(adjustedPrice)
price_median <- median(adjustedPrice)
price_10_percentile <- quantile(adjustedPrice, 0.1)
price_90_percentile <- quantile(adjustedPrice, 0.9)
price_skewness <- skewness(adjustedPrice)
price_kurtosis <- kurtosis(adjustedPrice)

price_summaryStatistics <- data.frame(
  Statistics = c('Mean', 'Std. Deviation', 'Minimum', 'P10', 'Median', 'P90', 'Maximum','Skewness', 'Kurtosis'),
  Values = round(c(price_mean, price_stdev, price_minimum, price_10_percentile, price_median, price_90_percentile, price_maximum, price_skewness, price_kurtosis), 6))

price_summaryStatistics

# Compute some relevant summary statistics of Log Returns
logReturns_mean <- mean(compoundedReturns)
logReturns_stdev <- sd(compoundedReturns)
logReturns_minimum <- min(compoundedReturns)
logReturns_maximum <- max(compoundedReturns)
logReturns_median <- median(compoundedReturns)
logReturns_10_percentile <- quantile(compoundedReturns, 0.1)
logReturns_90_percentile <- quantile(compoundedReturns, 0.9)
logReturns_skewness <- skewness(compoundedReturns)
logReturns_kurtosis <- kurtosis(compoundedReturns)

logReturns_summaryStatistics <- data.frame(
  Statistics = c('Mean', 'Std. Deviation', 'Minimum', 'P10', 'Median', 'P90', 'Maximum', 'Skewness', 'Kurtosis'),
  Values = round(c(logReturns_mean, logReturns_stdev, logReturns_minimum, logReturns_10_percentile, logReturns_median, logReturns_90_percentile, logReturns_maximum, logReturns_skewness, logReturns_kurtosis), 6))

logReturns_summaryStatistics
```

# Question 2

## a.
```{r echo=TRUE, fig.dim=c(5,4),fig.align='center'}
single_logReturns_df <- data.frame(compoundedReturns = compoundedReturns)

# Distribution Plot of daily log returns with equivalent normal distribution curve
ggplot(single_logReturns_df, aes(x = compoundedReturns)) +
  geom_histogram(aes(y = ..density..), 
                 bins = 50, fill = 'skyblue', color = 'white') +
  geom_density(aes(color = 'Empirical distribution'), size = 1) +
  stat_function(fun = dnorm,
                args = list(mean = mean(single_logReturns_df$compoundedReturns, na.rm = TRUE),
                            sd = sd(single_logReturns_df$compoundedReturns, na.rm = TRUE)),
                aes(color = 'Normal distribution'),
                linewidth = 1.5, linetype = 'dashed') +
  scale_color_manual(
    name = 'Distributions',
    values = c('Empirical distribution' = 'navy',
               'Normal distribution'   = 'orange')) +
  labs(title = 'Distribution of HSBC Daily Log Returns',
       x = 'Log Returns', y = 'Density') +
  theme_minimal() +
  theme(
    legend.position = 'bottom',
    legend.title = element_text(size = 12, face = 'bold'),
    legend.text = element_text(size = 10))
ggsave('figures/returns_distribution.png', dpi = 300)
```

## b.
```{r echo=TRUE, fig.dim=c(12,8)}
# Perform Jarque-Bera normality test
library(tseries)
jb_test <- jarque.bera.test(compoundedReturns)
jb_test

# Show the results of the JB test
jbTest_summaryStatistics <- data.frame(
  JB_Test_Statistic = round(jb_test$statistic, 2),
  Critical_Value = round(qchisq(0.95, 2), 2),
  p_Value = round(jb_test$p.value, 2) 
)

jbTest_summaryStatistics

# QQ Plot of daily log returns
ggplot(single_logReturns_df, aes(sample = compoundedReturns)) +
  stat_qq(shape = 1, color = 'blue', size = 1) +
  stat_qq_line(color = 'red', linewidth = 1) +
  labs(title = 'QQ Plot for HSBC Log Returns',
       x = 'Theoretical Quantiles', y = 'Sample Quantiles') +
  theme_minimal()
ggsave('figures/returns_qqplot.png', dpi = 300)
```